-- MySQL Script generated by MySQL Workbench
-- 11/10/16 14:18:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema int203_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema int203_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `int203_project` ;
USE `int203_project` ;

-- -----------------------------------------------------
-- Table `int203_project`.`AwardType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`AwardType` (
  `arwardTypeId` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`arwardTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int203_project`.`Award`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`Award` (
  `awardId` INT NOT NULL,
  `awardName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`awardId`),
  CONSTRAINT `fk_Award_AwardType1`
    FOREIGN KEY (`awardId`)
    REFERENCES `int203_project`.`AwardType` (`arwardTypeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `int203_project`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`Director` (
  `directorId` INT NOT NULL,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `bio` VARCHAR(255) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `nationality` VARCHAR(45) NULL DEFAULT NULL,
  `sex` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`directorId`));


-- -----------------------------------------------------
-- Table `int203_project`.`Studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`Studio` (
  `studioIn` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`studioIn`));


-- -----------------------------------------------------
-- Table `int203_project`.`TypeMovie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`TypeMovie` (
  `typeMovieId` INT NOT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`typeMovieId`));


-- -----------------------------------------------------
-- Table `int203_project`.`SoundtrackGenre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`SoundtrackGenre` (
  `genreId` INT NOT NULL,
  `genreType` VARCHAR(45) NULL,
  PRIMARY KEY (`genreId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int203_project`.`SoundtrackCompressor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`SoundtrackCompressor` (
  `compressorId` INT NOT NULL,
  `compressorName` VARCHAR(50) NULL,
  PRIMARY KEY (`compressorId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int203_project`.`Soundtrack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`Soundtrack` (
  `soundtrackId` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `genreId` INT NOT NULL,
  `compressorId` INT NOT NULL,
  PRIMARY KEY (`soundtrackId`),
  INDEX `fk_Soundtrack_SoundtrackGenre1_idx` (`genreId` ASC),
  INDEX `fk_Soundtrack_SoundtrackCompressor1_idx` (`compressorId` ASC),
  CONSTRAINT `fk_Soundtrack_SoundtrackGenre1`
    FOREIGN KEY (`genreId`)
    REFERENCES `int203_project`.`SoundtrackGenre` (`genreId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Soundtrack_SoundtrackCompressor1`
    FOREIGN KEY (`compressorId`)
    REFERENCES `int203_project`.`SoundtrackCompressor` (`compressorId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `int203_project`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`Movie` (
  `movieId` INT NOT NULL,
  `movieName` VARCHAR(50) NULL DEFAULT NULL,
  `boxOffice` DOUBLE NULL DEFAULT NULL,
  `duration` DOUBLE NULL DEFAULT NULL,
  `rating` DOUBLE NULL DEFAULT NULL,
  `releaseDate` DATE NULL,
  `soundtrackId` INT NOT NULL,
  `directorId` INT NOT NULL,
  `awardId` INT NULL,
  `studioId` INT NOT NULL,
  `typeMovie` INT NOT NULL,
  PRIMARY KEY (`movieId`),
  INDEX `fk_Movie_Director1_idx` (`directorId` ASC),
  INDEX `fk_Movie_Studio1_idx` (`studioId` ASC),
  INDEX `fk_Movie_TypeMovie1_idx` (`typeMovie` ASC),
  INDEX `fk_Movie_Soundtrack1_idx` (`soundtrackId` ASC),
  INDEX `fk_Movie_Award1_idx` (`awardId` ASC),
  CONSTRAINT `fk_Movie_Director1`
    FOREIGN KEY (`directorId`)
    REFERENCES `int203_project`.`Director` (`directorId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Movie_Studio1`
    FOREIGN KEY (`studioId`)
    REFERENCES `int203_project`.`Studio` (`studioIn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Movie_TypeMovie1`
    FOREIGN KEY (`typeMovie`)
    REFERENCES `int203_project`.`TypeMovie` (`typeMovieId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Movie_Soundtrack1`
    FOREIGN KEY (`soundtrackId`)
    REFERENCES `int203_project`.`Soundtrack` (`soundtrackId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Movie_Award1`
    FOREIGN KEY (`awardId`)
    REFERENCES `int203_project`.`Award` (`awardId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `int203_project`.`Starring`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`Starring` (
  `starringId` INT NOT NULL,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `bio` VARCHAR(255) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `nationality` VARCHAR(45) NULL DEFAULT NULL,
  `sex` VARCHAR(10) NULL DEFAULT NULL,
  `awardId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`starringId`));


-- -----------------------------------------------------
-- Table `int203_project`.`StuntMan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`StuntMan` (
  `stuntManId` INT NOT NULL,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `bio` VARCHAR(255) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `sex` VARCHAR(10) NULL DEFAULT NULL,
  `nationality` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`stuntManId`));


-- -----------------------------------------------------
-- Table `int203_project`.`Trailer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`Trailer` (
  `trailerId` INT NOT NULL,
  `link` VARCHAR(255) NULL DEFAULT NULL,
  `movieId` INT NOT NULL,
  PRIMARY KEY (`trailerId`),
  INDEX `fk_Trailer_Movie1_idx` (`movieId` ASC),
  CONSTRAINT `fk_Trailer_Movie1`
    FOREIGN KEY (`movieId`)
    REFERENCES `int203_project`.`Movie` (`movieId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `int203_project`.`DirectorAward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`DirectorAward` (
  `directorId` INT NOT NULL,
  `awardId` INT NOT NULL,
  INDEX `fk_DirectorAward_Award_idx` (`awardId` ASC),
  INDEX `fk_DirectorAward_Director1_idx` (`directorId` ASC),
  CONSTRAINT `fk_DirectorAward_Award`
    FOREIGN KEY (`awardId`)
    REFERENCES `int203_project`.`Award` (`awardId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DirectorAward_Director1`
    FOREIGN KEY (`directorId`)
    REFERENCES `int203_project`.`Director` (`directorId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int203_project`.`MovieActor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`MovieActor` (
  `movieId` INT NOT NULL,
  `starringId` INT NOT NULL,
  `stuntManId` INT NULL,
  PRIMARY KEY (`movieId`, `starringId`),
  INDEX `fk_MovieActor_Starring1_idx` (`starringId` ASC),
  INDEX `fk_MovieActor_StuntMan1_idx` (`stuntManId` ASC),
  CONSTRAINT `fk_MovieActor_Movie1`
    FOREIGN KEY (`movieId`)
    REFERENCES `int203_project`.`Movie` (`movieId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_MovieActor_Starring1`
    FOREIGN KEY (`starringId`)
    REFERENCES `int203_project`.`Starring` (`starringId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_MovieActor_StuntMan1`
    FOREIGN KEY (`stuntManId`)
    REFERENCES `int203_project`.`StuntMan` (`stuntManId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `int203_project`.`StarringAward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `int203_project`.`StarringAward` (
  `starrtingId` INT NOT NULL,
  `awardId` INT NOT NULL,
  INDEX `fk_StarringAward_Starring1_idx` (`starrtingId` ASC),
  INDEX `fk_StarringAward_Award1_idx` (`awardId` ASC),
  CONSTRAINT `fk_StarringAward_Starring1`
    FOREIGN KEY (`starrtingId`)
    REFERENCES `int203_project`.`Starring` (`starringId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_StarringAward_Award1`
    FOREIGN KEY (`awardId`)
    REFERENCES `int203_project`.`Award` (`awardId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
